### ISSUE TITLE
Can we move tcp/udp/any into the object, instead of the policy?

### ISSUE THREAD

**Issue by mgmoerman** [job/aclhound#17]
It is nicer to define the object as what it actually is, instead of  having to define  multiple policies. For example, DNS is both TCP & UDP, it requires then 2 policy entries in a policy file, while you could better define the object as both  TCP & UDP

**Comment by job** [comment]
I will create a new protocol called "tcpudp" which is a short hand to allow/deny both protocols. This should solve the problem for services which rely on both.
