### ISSUE TITLE
not converting wrong ipv6 host ip into an ipv6 network

### ISSUE THREAD

**Issue by mylex666** [job/aclhound#29]
example:
ipv6 access-list test-in-v6 permit tcp 2001:630:440:400::1/64 any

asa output:
ipv6 access-list test-in-v6 line 1 permit tcp 2001:630:440:400::/64 any (hitcnt=0) 0x6fccbeda

**Comment by job** [comment]
After discussion: "2001::1/64" should throw a compile error as its neither a proper host nor a proper network specification. in 'ipaddr' i can compare
