### ISSUE TITLE
Feature request: Please add the possibility to add a timeout when save_config flag is set

### ISSUE THREAD

**Issue by mgmoerman** [job/aclhound#39]
This is a feature request. Right now, if you run aclhound and the save_config is set to true, when saving the config back to nvram on a cisco, and the config is big and it takes quite some time. Deploy will return not successfull, as it doesn't wait until the config is actually written. (Especially annoying if you run it from jenkins)

**Comment by job** [comment]
This is fixed by 9b0487a0ed7ccadbdd9c08797d05cf3a872a4713
