### ISSUE TITLE
Detection of duplicate statements.

### ISSUE THREAD

**Issue by amd762mpx** [job/aclhound#48]
We were in a situation where duplicate statements/lines were configured in a policy, with a small policy this is easy to catch but by time policies are growing and therefore less evident to spot duplicates.

Can this be checked somewhere in the verification process ? Of course comments should be excluded from this. Not high priority.

**Comment by job** [comment]
The compiler _should_ remove duplicate firewall statements, do you have an example where this does not happen?

**Comment by amd762mpx** [comment]
If the compiler removes the duplicate firewall statements, that does not prevent users from adding duplications in a policy which leads to possible "pollution". I am not worried for the firewall, I want keep the policy tidy. Can the compiler report on duplications in a policy?

**Comment by job** [comment]
Sorry, because of the (possibly recursive) @ policy in policy inclusion you can do, I cannot make a reliable duplicate detector. Maybe once in a while run ```sort $file | uniq -c -d``` and manually decide what you want to do?

**Comment by amd762mpx** [comment]
Policy:
allow tcp src @abc port any dst @-xyz_mysql port @mysql_services
allow tcp src @abc port any dst @-xyz_mysql port @mysql_services

During an "aclhound build all" can you make it happen it will check for duplicates?
