### ISSUE TITLE
Splitting on port ranges

### ISSUE THREAD

**Issue by gdelaney** [job/aclhound#52]
```
allow tcp src 10.10.10.1 port 32766-32768 dst 10.10.11.0/24 stateful
```
Returns 2 acls
```
   permit tcp host 10.10.10.1 eq 32768 10.10.11.0 0.0.0.255 established
   permit tcp host 10.10.10.1 range 32766 32767 10.10.11.0 0.0.0.255 established
```

Is split it into 2 rules, because the set() on the port range 32766-32768 returns 2 items in https://github.com/gdelaney/aclhound/blob/master/aclhound/aclsemantics.py#L233

https://github.com/job/aclhound/pull/51

**Comment by jzohrab** [comment]
@gdelaney what is the preferred solution here?  That a separate rule be generated for each entry, or that it be combined into a range?  (newbie question, just looking at this project but will PR if I can address this).

**Comment by job** [comment]
Oh this issue can be closed, it was resolved by https://github.com/job/aclhound/commit/6d0543442b631df1b045c8520f69cdecf2c6015e
