### ISSUE TITLE
Not sure about ACLHound workflow

### ISSUE THREAD

**Issue by jzohrab** [job/aclhound#57]
From the guide, it appears that I can use ACLHound to actually deploy ACLs, but I've seen notes around that imply that the changes are getting committed to a git repo or similar for code review before getting pushed out to the actual devices.  That would be a very nice feature, allowing for a code review prior to configurations getting pushed out to devices.

Is there a doc, that I've missed, explaining such a workflow? The TODO has "Subcommands to be created - aclhound diff" etc, so maybe this is work-in-progress somewhere.

This may be quicker to discuss via skype or similar, if you are available and interested.  I'm doing a comparison of a few ACL automation tools, and have assessed this and Google's Capirca.

Thanks, jz

**Comment by mgmoerman** [comment]
Hey,

There is some documentation on jenkins integration here: https://github.com/job/aclhound/blob/master/INSTALL-CONFIG.md

And basically, aclhound has a directory, if you just push that to a repository and use something like gerrit to do approvals (like we at eCG do) it shouldn't be a problem.

the extra commands in aclhound (like reset and diff) are something that i guess we're gonna abandon as they are just aliases for git commands

**Comment by jzohrab** [comment]
Hello @mgmoerman, thanks for the response.  I read that config, but still wasn't clear on usage.

The `aclhound build` command returns the following to stdout:

```
(venv) $ aclhound build ~/aclhound/devices/fw001
INFO: working with data in /Users/jzohrab/aclhound
INFO: building configuration for /Users/jzohrab/aclhound/devices/fw001

Seed policy name: x
   IPv4:
   access-list x-v4 extended permit tcp 10.32.1.0 255.255.255.0 10.32.2.0 255.255.255.0 eq [22]
   access-list x-v4 extended permit tcp 10.32.1.0 255.255.255.0 10.32.2.0 255.255.255.0 eq [80]
   access-list x-v4 extended permit tcp 10.32.1.0 255.255.255.0 10.32.2.0 255.255.255.0 eq [443]
   access-list x-v4 extended deny ip any any
     ---------
   IPv6:
   ipv6 access-list x-v6 deny ip any any
```

This is output to stdout, I couldn't see a built in command to save to a directory.  Do you recommend that I run this command and redirect to output, and then commit that?

The issue I thought of for redirecting and saving is that things may change.  The redirected data would be a representation of the actual changes I will run on the device, and not the actual changes themselves.  When aclhound actual deploys the changes, it will again read from the source files, and update the devices - but if the source files have changed, then it wouldn't match the data that I had saved earlier.

Can ACLHound this redirected output and use that for its config changes?  As far as I can see from the code and examples, it doesn't.

**Comment by mgmoerman** [comment]
It's not intended for saving the configuration. You use 'aclhound build all' or 'aclhound build devices/blabla' for deploying ACLs to the device.

**Comment by jzohrab** [comment]
Got it, thanks @mgmoerman.  Ah, and when you were saying "aclhound has a directory", you were referring to the `~/aclhound` directory which has the definitions/devices/policyfiles, and then that's used to push.  For some reason, I was thinking that you'd generate, files, commit, push, and review those before applying, which is wrong - don't know why I missed that.  I'll submit a small PR for a docs update.

**Comment by jzohrab** [comment]
Closing, PR issued.
